# Generated by Django 3.2.9 on 2021-11-27 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(db_index=True, max_length=50, verbose_name='Инвентарный номер')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание установки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('image', models.ImageField(upload_to='оборудование', verbose_name='Путь хранения')),
                ('qr', models.ImageField(upload_to='qr', verbose_name='QR code')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='check', verbose_name='Путь хранения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.tasksmodel', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='CheckListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('check', models.BooleanField(default=False, verbose_name='Проверка')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.tasksmodel', verbose_name='Чек лист')),
            ],
            options={
                'verbose_name': 'Check list',
                'verbose_name_plural': 'Check list',
            },
        ),
    ]
