# Generated by Django 3.2.9 on 2021-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_checklistmodel_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmodel',
            name='check',
            field=models.BooleanField(default=None, null=True, verbose_name='Проверка'),
        ),
    ]
